server:
  port: 8004 #端口号
  servlet-path: /pointmng
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml #mybatis配置文件的路径
  type-aliases-package: system.dept.model #所有实体类

  mapper-locations: classpath:mybatis/mapper/*.xml #mapper映射的文件
spring:
  application:
    name: microSerivceCloud-dept #对外曝光微服务名称
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/voucher2?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
    dbcp2:
      min-idle: 6
      nitial-size: 6
      max-total: 6
      max-wait-millis: 200
eureka:
  client: #客户端注册进行eureka服务列表
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka
  instance:
    instance-id: microSerivceCloud-dept8004 #别名
    prefer-ip-address: true
info:
  app.name: microSerivceCloud-dept #工程名称
  company.name: www.xianyue.com #公司网址
  build.artifactId: $project.artifactId$ #灵活的调用在父工程有配置build
  build.version: $project.version$